watchers:
  - path: "/Users/username/Downloads"
    recursive: true
    rules:
      - event: "created"
        conditions:
          - type: "extension"
            value: "jpg"
        actions:
          - type: "move"
            destination: "/Users/username/Pictures/"
            overwrite: "suffix"
      - event: "modified"
        conditions:
          - type: "extension"
            value: "pdf"
        actions:
          - type: "move"
            destination: "/Users/username/Documents/PDFs/{filename}"
            overwrite: "overwrite"
      - event: "created"
        conditions:
          - type: "glob"
            value: "*.txt"
        actions:
          - type: "exec"
            command: "/usr/bin/echo"
            args: ["New file:", "{filename}"]
            env:
              - ["SRC_PATH", "{path}"]
              - ["FILE_NAME", "{name}.{ext}"]
              - ["TODAY", "{date}"]
